Models/Address.cs
using System.ComponentModel.DataAnnotations;

namespace RunGroupWebApp.Models
{
    public class Address
    {
        [Key]
        public int Id { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }

    }
}

Models/AppUser.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace RunGroupWebApp.Models
{
    public class AppUser
    {
        [Key]
        public string Id { get; set; }
        public int? Pace { get; set; }
        public int? Mileage { get; set; }
        public Address? Address { get; set; }
        public ICollection<Club> Clubs { get; set; }
        public ICollection<Race> Race { get; set; }
    }
}

Models/Club.cs
using RunGroupWebApp.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunGroupWebApp.Models
{
    public class Club
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        [ForeignKey("Address")]
        public int? AddressId { get; set; }
        public Address? Address { get; set; }
        public ClubCategory ClubCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace RunGroupWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Race.cs
using RunGroupWebApp.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunGroupWebApp.Models
{
    public class Race
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string? Image { get; set; }
        public DateTime? StartTime { get; set; }
        public int? EntryFee { get; set; }
        public string? Website { get; set; }
        public string? Twitter { get; set; }
        public string? Facebook { get; set; }
        public string? Contact { get; set; }
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
        public RaceCategory RaceCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroupWebApp.Data;
using RunGroupWebApp.Models;

namespace RunGroupWebApp.Controllers
{
    public class ClubController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ClubController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Club> clubs = _context.Clubs.ToList();
            return View(clubs);
        }

        public IActionResult Detail(int id)
        {
            Club club = _context.Clubs.Include(x => x.Address).FirstOrDefault(c => c.Id == id);
            return View(club);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RunGroupWebApp.Models;
using System.Diagnostics;

namespace RunGroupWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroupWebApp.Data;
using RunGroupWebApp.Models;

namespace RunGroupWebApp.Controllers
{
    public class RaceController : Controller
    {
        private readonly ApplicationDbContext _context;
        public RaceController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Race> races = _context.Races.ToList();
            return View(races);
        }
        public IActionResult Detail(int id)
        {
            Race race = _context.Races.Include(x => x.Address).FirstOrDefault(c => c.Id == id);
            return View(race);
        }
    }
}

Views/Club/Detail.cshtml
@model Club
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <h1 class="my-4">
        Header
        <small>secondary</small>
    </h1>

    <div class="row">
        <div class="col-8">
            <img class="img-fluid" src="https://i2.wp.com/beginogi.ru/wp-content/uploads/2016/11/na-golodnuj-jeludok.jpg" alt="" />
        </div>

        <div class="col-4">
            <h3 class="my-3">@Model.Title</h3>
            <p class="my-3">@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City</li>
                <li>@Model.Address.State</li>
                <li>@Model.ClubCategory</li>
                <li></li>
            </ul>
        </div>
    </div>

    <h3 class="my-4"></h3>

    <div class="row">
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
    </div>
</div>

Views/Club/Index.cshtml
@model IEnumerable<Club>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1 class="text-center mb-3">Клубы пробежек</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card shadow-sm">
                <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="https://i2.wp.com/beginogi.ru/wp-content/uploads/2016/11/na-golodnuj-jeludok.jpg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">

                <div class="card-body">
                    <p class="card-text">@item.Title</p>
                    <p class="card-text">@item.Description</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">@item.ClubCategory</small>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Race/Detail.cshtml
@model Race
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <h1 class="my-4">
        Header
        <small>secondary</small>
    </h1>

    <div class="row">
        <div class="col-8">
            <img class="img-fluid" src="https://i2.wp.com/beginogi.ru/wp-content/uploads/2016/11/na-golodnuj-jeludok.jpg" alt="" />
        </div>

        <div class="col-4">
            <h3 class="my-3">@Model.Title</h3>
            <p class="my-3">@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City</li>
                <li>@Model.Address.State</li>
                <li>@Model.RaceCategory</li>
                <li></li>
            </ul>
        </div>
    </div>

    <h3 class="my-4"></h3>

    <div class="row">
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
        <div class="col-md-3 col-sm-6 mb-4">
            <a href="">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="" />
            </a>
        </div>
    </div>
</div>

Views/Race/Index.cshtml
@model IEnumerable<Race>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1 class="text-center mb-3">Трассы пробежек</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card shadow-sm">
                <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="https://i2.wp.com/beginogi.ru/wp-content/uploads/2016/11/na-golodnuj-jeludok.jpg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">

                <div class="card-body">
                    <p class="card-text">@item.Title</p>
                    <p class="card-text">@item.Description</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a asp-controller="club" asp-action="Detail" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">@item.RaceCategory</small>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RunGroupWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RunGroupWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RunGroupWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Race" asp-action="Index">Race</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Index">Club</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RunGroupWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>